### PR TITLE
feat: Token rotation will use its own endpoint and tests will run against self-hosted GitLab CE

### PR DESCRIPTION
**Pull request by ilijamt**

### CODE REVIEW

**Comment by cm3brian** [comment]
As requested in #89, I have given it a quick, isolated test for our use-case (being GitLab Cloud). Sorry for not being able to dig super-deep here, however, I'm heading off early today :)

It seems that I still cannot rotate the main token, however instead of a permissions' error it's giving "unsupported operation", which is new...
Screenshot 2024-07-12 at 11 51 21 AM

versus the current release version, doing the same (similar config as example above provided to it):
Screenshot 2024-07-12 at 12 22 01 PM

**Comment by ilijamt** [comment]
I updated the endpoint. So now it's `vault write -f gitlab/config/rotate`

**Comment by ilijamt** [comment]
@TJM Any chance you can test this as well? And I'm interested if the issue persists with the TTL?

**Comment by ilijamt** [comment]
@cm3brian is it working for you now?

**Comment by cm3brian** [comment]
@ilijamt I can confirm that the rotation of the main user token used from gitlab.com is successful now
image

I can confirm that project and group tokens working as expected.

Can also confirm that you may not create token_type=personal on gitlab.com as this requires "admin" and only self-hosted or dedicated instances (for some reason) allow this through the Admin API. This is known in the readme already, but I also tested it just incase.

**Pull request merged**
