### PR TITLE
feat(issue-102): add service account token type for gitlab.com accounts

### PR DESCRIPTION
**Pull request by GavinCS**

### CODE REVIEW

**Comment by ilijamt** [comment]
@GavinCS I was going through the documentation of GitLab and I saw that there are two types of service accounts, one are User Service Accounts (the one that require admin access), and the other ones are Group Service Accounts. Both require at least Premium Tier subscription. At the moment, I don't have access to the subscription. Do you by any chance can help me test on the Premium account or if you can give access to my user, so I can test it? 

I created #110 that would allow us to select the proper GitLab type and service account type.

**Comment by ilijamt** [comment]
I've also asked GitLab Sales if they can provide a license, so I can fully test and develop the service account features. Hopefully they come back with a positive reply.

**Comment by GavinCS** [comment]
@ilijamt I won't be able to give you access to our Group in Gitlab but I could probably setup an isolated group that we can test with. Gitlab providing a license would be first class - If you gice me the details of your ticket I can also try push with our account manager

**Comment by ilijamt** [comment]
Finally got the license. So I'll get this finished soon.

**Comment by ilijamt** [comment]
Implemented in #110

**Pull request closed without merging**
